### ISSUE TITLE
Help wanted : db.sqlite3

### ISSUE THREAD

**Issue by SoheeLee** [swsnu/swpp17-team12#41]
Dear Team 12, I'm in great need of `db.sqlite3` file

1. which works well on remote `api-team` branch
1. which also has many (5 or more - more is better!) rating records made by one user
1. and the username and password of the user
1. and the username and password of the superuser(admin).

It would be very tiresome to make such sqlite3 file, but I really need it for my future implementation of `My Page` and I can't make it on my own due to current issue. Your help will be very appreciated. Thank you!

**Comment by shinandruth** [comment]
ㅠㅠ im on the same page as you. sorry:(

**Comment by jhbaang** [comment]
@SoheeLee 
I am sorry to hear that. I don't know why chrome extension is not work for your environment...
Here is my [`db.sqlite3`](https://www.dropbox.com/s/u36snfse4s4r3gf/db.sqlite3?dl=0) file.
> admin user: id - `jhbang` / pwd - `bangbang`
> user: id - `user1` / pwd - `user1`
I really wish this is helpful to you.
thankyou.

**Comment by SoheeLee** [comment]
There are many ratings in the db! Thanks a lot! :)
